pipeline:
  identifier: Build_Gopajit_gradle_example_1718792632204
  name: gopajit-gradle-example
  orgIdentifier: default
  projectIdentifier: GopajitGradleProject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Gopajit/gradle-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: gradle-build
                  identifier: gradlebuild
                  spec:
                    shell: Sh
                    command: gradle build
              - step:
                  type: RunTests
                  name: gradle-test
                  identifier: gradletest
                  spec:
                    language: Java
                    buildTool: Gradle
                    args: clean test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
